workspace:
  base: /go/src
  path: github.com/appleboy/go-twzipcode-plugin

pipeline:
  build:
    image: appleboy/golang-testing:1.8.0
    environment:
      - GOPATH=/go
    commands:
      - make embedmd
      - make bindata
      - make plugin
      - make test

  github:
    image: plugins/github-release
    pull: true
    api_key: ${GITHUB_RELEASE_API_KEY}
    files:
      - go-twzipcode.so
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  facebook:
    image: appleboy/drone-facebook
    pull: true
    to: 1234973386524610
    fb_page_token: ${FB_PAGE_TOKEN}
    fb_verify_token: ${FB_VERIFY_TOKEN}
    when:
      status: [ success, failure ]
