workspace:
  base: /go/src
  path: github.com/appleboy/go-twzipcode-plugin

pipeline:
  build:
    image: appleboy/golang-testing:1.8.0
    environment:
      - GOPATH=/go
    commands:
      - make embedmd
      - make bindata
      - make plugin
      - make test

  facebook:
    image: appleboy/drone-facebook
    pull: true
    to: 1234973386524610
    fb_page_token: ${FB_PAGE_TOKEN}
    fb_verify_token: ${FB_VERIFY_TOKEN}
    when:
      status: [ success, failure ]

matrix:
  GO_VERSION:
    - 1.6.4
    - 1.7.5
    - 1.8.0
